CREATE TABLE IF NOT EXISTS pedidos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    situacao_pedido VARCHAR(50) NOT NULL,
    data_emissao VARCHAR(50) NOT NULL,
    data_validade VARCHAR(50),
    cliente_id INT,
    cliente_nome VARCHAR(255),
    vendedor_id INT,
    vendedor_nome VARCHAR(255),
    origem_venda VARCHAR(100),
    tipo_frete VARCHAR(50),
    transportadora_id INT,
    transportadora_nome VARCHAR(255),
    valor_frete DECIMAL(10, 2),
    total DECIMAL(10, 2) NOT NULL,
    desconto_total DECIMAL(10, 2),
    total_com_desconto DECIMAL(10, 2) NOT NULL,
    lista_itens JSON, -- Para armazenar uma lista de itens em formato JSON
    formas_pagamento JSON, -- Para armazenar as formas de pagamento em formato JSON
    observacao TEXT,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_finalizacao VARCHAR(50),
    ordem_finalizacao VARCHAR(50),
    endereco_expedicao VARCHAR(255),
    hora_expedicao VARCHAR(50),
    usuario_expedicao VARCHAR(100),
    numero_nf VARCHAR(50),
    data_nf VARCHAR(50),
    tecnospeed_id VARCHAR(255),
    tecnospeed_id_integracao VARCHAR(255),
    tecnospeed_status VARCHAR(50)
);